name: lms_task
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  dio: ^5.4.0
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.1
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  injectable: ^2.5.0
  persistent_bottom_nav_bar: ^6.2.1
  loading_animation_widget: ^1.2.1

  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^9.1.1
  vimeo_video_player: ^0.0.16

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
